### ISSUE TITLE
Error in data.table::setnames: 'old' is length 7 but 'new' is length 2

### ISSUE THREAD

**Issue by deb0612** [honzee/RNAseqCNV#18] opened 2023-02-17 10:05 UTC
Dear sir,
when I tried to apply RNAseqCNV either by shinnyapp or by command, it show the error message below:
![image](https://user-images.githubusercontent.com/29038270/219613961-3ca6d0be-f247-4116-bd6a-d65934a49dbd.png)
My read counts was generated from featurecounts.
"command: featureCounts -T 10 -a GENCODE28.gtf -o read.count -p -B -C -f -t exon -g gene_id  *.bam"
Is that the wrong format of my GTF file?

**Comment by honzee** [comment] 2023-02-17 10:25
Hi,

thank you for trying out our package!

I think this might be caused by incorrectly formatted counts file. It is expected to have two columns (https://github.com/honzee/RNAseqCNV#213-read-count-file-), but I think your has 7. Could you send the first few lines for your counts file to validate this?

If this is the case, I would suggest to reformat the input count files.

Best,
Jan

**Comment by deb0612** [comment] 2023-02-18 11:53
The count file looked like this:
Geneid  Chr     Start   End     Strand  Length  A2969_S226_L003.pb.hg38.bam
ENSG00000223972.5       1       11869   12227   +       359     0
ENSG00000223972.5       1       12613   12721   +       109     0
ENSG00000223972.5       1       13221   14409   +       1189    1
ENSG00000223972.5       1       12010   12057   +       48      0
ENSG00000223972.5       1       12179   12227   +       49      0
ENSG00000223972.5       1       12613   12697   +       85      0
ENSG00000223972.5       1       12975   13052   +       78      1
ENSG00000223972.5       1       13221   13374   +       154     0

**Comment by deb0612** [comment] 2023-02-20 05:59
I tried to reformat my count file, however there are other problem
![image](https://user-images.githubusercontent.com/29038270/220021734-9e522c42-7849-467e-96db-e413e7fa7a4f.png)

**Comment by honzee** [comment] 2023-02-20 07:41
Could you test it in console using the wrapper function - we might get more information that way. Also, could you please send the header of one of the count files again? It seems they are not being read correctly.

Best,
Jan

**Comment by deb0612** [comment] 2023-02-21 07:56
In console
![image](https://user-images.githubusercontent.com/29038270/220282497-bdd35f9f-636e-48a2-ba0b-92de99ce776d.png)

header of count file
![image](https://user-images.githubusercontent.com/29038270/220282622-1f43db38-8b1b-4286-be47-f9f5fdb77d35.png)

**Comment by honzee** [comment] 2023-02-25 21:49
Looking again at the count data matrix, the ensemble IDs are not correctly formatted. RNAseqCNV expects unique ensemble gene ids but multiple rows have the same ensemble id.

I suggest collapsing all rows with the same ensemble id together. 

Best,
Jan

**Comment by 1-WestYoung** [comment] 2024-12-31 02:17
I encountered a similar problem and it was resolved by removing the '.' from the geneid：ENSG00000290825.2------ENSG00000290825

**Closed as completed** 2024-12-31 09:59 UTC
